export const COLORS = {
  background: '#F5F0E8',
  card: '#FFFDF7',
  primary: '#C96B3A',
  primaryLight: '#FAE8DB',
  text: '#2C1A0E',
  textSecondary: '#9A7B5A',
  border: '#E8DDD0',
  danger: '#C53030',
  success: '#5A8A5A',
  white: '#FFFDF7',
  accent: '#8B4A20',
  mint: '#E8F0E4',
  lavender: '#EDE8F5',
  sand: '#FFF4E0',
  blue: '#E8EFF5',
  peach: '#FFEAE0',
  yellow: '#FFF5D6',
  inkSoft: '#4A3728',
  panel: '#EDE6D8',
  teal: '#5B8C7A',
  grape: '#8B6BAE',
};

export const MOODS = [
  { label: 'Great', color: '#6CC97C', value: 5 },
  { label: 'Good',  color: '#F9C74F', value: 4 },
  { label: 'Okay',  color: '#C5A8E8', value: 3 },
  { label: 'Low',   color: '#F4A56A', value: 2 },
  { label: 'Bad',   color: '#89B4D4', value: 1 },
];
